# Generated by Django 5.1.1 on 2024-10-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment_day",
            new_name="payment_date",
        ),
    ]
