# Generated by Django 5.1.1 on 2024-10-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_amount",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="введите сумму оплаты",
                null=True,
                verbose_name="оплата",
            ),
        ),
    ]
