# Generated by Django 5.1.1 on 2024-10-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="update_at",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="дата обновления курса"
            ),
        ),
    ]
