# Generated by Django 5.1.1 on 2024-10-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_course_update_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="update_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="дата обновления курса"
            ),
        ),
    ]
